import { Project, SyntaxKind } from 'ts-morph'
import fs from 'fs'
import path from 'path'
import prettier from 'prettier'
import { fileURLToPath } from 'url'

// ------------------ Node ESM 获取 __dirname ------------------
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// ------------------ 配置 ------------------
const ROUTES_DIR = path.resolve(__dirname, 'src/routes')
const OUTPUT_FILE = path.resolve(__dirname, 'src/api/generated.ts')

// ------------------ 初始化 ts-morph ------------------
const project = new Project({
  tsConfigFilePath: path.resolve(__dirname, 'tsconfig.json'),
})

// 扫描所有 routes
project.addSourceFilesAtPaths(path.join(ROUTES_DIR, '**/*.ts'))
const sourceFiles = project.getSourceFiles()

const functions = []

for (const file of sourceFiles) {
  const calls = file.getDescendantsOfKind(SyntaxKind.CallExpression)

  calls.forEach((call) => {
    const expr = call.getExpression().getText()
    if (!expr.startsWith('router.')) return

    const method = expr.replace('router.', '').toUpperCase()
    const args = call.getArguments()
    if (args.length < 2) return

    const pathArg = args[0].getText().replace(/['"`]/g, '')

    // 函数名：根据路径生成
    const fnName = pathArg
      .replace(/\//g, '_')
      .replace(/[:{}]/g, '')
      .replace(/[^a-zA-Z0-9_]/g, '')
      .replace(/^_+/, '')

    // body 类型
    let bodyType = 'any'
    if (method === 'POST' || method === 'PUT') {
      const fnNode = args[1]
      const paramTypes = fnNode.getDescendantsOfKind(SyntaxKind.TypeReference)
        .map((t) => t.getText())
        .filter((t) => !t.includes('Promise')) // 排除返回类型
      if (paramTypes.length) bodyType = paramTypes[0]
    }

    // GET 参数类型
    let queryType = '{}'
    if (method === 'GET' || method === 'DELETE') {
      queryType = '{}'
    }

    const responseType = 'any'

    const fnCode = `/** ${pathArg} ${method} */
export async function ${fnName}(
  ${method === 'GET' || method === 'DELETE' ? 'params: API.' + queryType : 'params: API.' + bodyType},
  options?: CustomAxiosRequestConfig
) {
  return request<API.${responseType}>('${pathArg}', {
    method: '${method}',
    ${method === 'GET' || method === 'DELETE' ? 'params' : 'data'}: params,
    ...(options || {})
  })
}`
    functions.push(fnCode)
  })
}

// ------------------ 写入文件 ------------------
const content = `
/**
 * This file is auto-generated by generate-api.mjs
 * Do not edit manually
 */
import request, { CustomAxiosRequestConfig } from '@/utils/request'

${functions.join('\n\n')}
`

const formatted = await prettier.format(content, { parser: 'typescript' })
fs.writeFileSync(OUTPUT_FILE, formatted, 'utf8')

console.log('✅ API functions generated:', OUTPUT_FILE)